apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        build_number: ${build_tag}
        app: ${img_name}
        role: rolling-update
  name: ${img_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      build_number: ${build_tag}
      app: ${img_name}
      role: rolling-update
  template:
    metadata:
      labels:
        build_number: ${build_tag}
        app: ${img_name}
        role: rolling-update
    spec:
      containers:
      - name: ${img_name}       
        image: ${docker_img_name}
        ports:
        - containerPort: 8080


