apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        app: ${img_name}
  name: ${img_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${img_name}
  template:
    metadata:
      labels:
        app: ${img_name}
    spec:
      containers:
      - name: ${img_name}       
        image: ${docker_img_name}
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  labels:
        app: ${img_name}
  name: ${img_name}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
        app: ${img_name}
